# 系统参数注入
austin:
  nacos:
    server: ${spring.cloud.nacos.server-addr}
    group: ${spring.cloud.nacos.discovery.group}
    dataId: ${spring.application.name}-${spring.profiles.active}.yaml
    namespace: ${spring.cloud.nacos.discovery.namespace}